version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      APS_CLIENT_ID: ${APS_CLIENT_ID}
      APS_CLIENT_SECRET: ${APS_CLIENT_SECRET}
      APS_BUCKET: ${APS_BUCKET}
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3001
    depends_on:
      - backend
